spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db_init.sql
  datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:share-with-me
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: postgres

logging:
  level:
    ru.practicum.ewm.stats: "debug"

feign:
  client:
    config:
      default:
        loggerLevel: "FULL"