#Kafka properties
collector:
  kafka:
    producer:
      user-action-topic: stats.user-actions.v1

spring:
  kafka:
    producer:
      properties:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: ru.practicum.ewm.stats.serialization.AvroSerializer

#gRPC properties
grpc:
  server:
    port: 0