spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db_init.sql
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/main
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-requests
    username: postgres
    password: postgres