server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db_init.sql
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:share-with-me
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/stats
    username: postgres
    password: postgres
    #spring.datasource.driverClassName=org.h2.Driver
    #spring.datasource.url=jdbc:h2:mem:share-with-me